### ISSUE TITLE
README / repository description is not clear.

### ISSUE THREAD

**Issue by vi** [crate-ci/stager#15]
> Stage files for packaging 

That's the only content phrase.

What is "staging"? What is "packaging"? Is it Git's staging of files for making a commit? Is it Cargo's packaging prior to publishing to crates.io?

There should be more text (especially about broader context), some example, maybe some diagram, maybe console output.

Module-level reference documentation is also not clear:

> stager - This crate stages files for packaging
>  Modules:
> action | Filesystem operations to stage files.
> builder | High-level requirements for staging files.
> de | Composable file format for staging files.

**Comment by epage** [comment]
The downside of rushing to get a prototype of this and cargo-tarball out.  Hopefully #16 helps clarify.

**Comment by vi** [comment]
Suggested repository description (which is not updated yet):

`A tool to package executables from Rust-based project into a release bundle based on configuration file`

(if I understood this correctly).

A sample of such configuration file and layount of the resulting archive (`tar -tf ...` output) is still missing.

> projct

...

**Comment by epage** [comment]
I've separately created #17 for documenting the schema.  cargo-tarball for now will be the best most complete example since it will be dog fooding itself.  It would be nice to add additional detail of how it is an example but I don't feel that is as pressing.
