### ISSUE TITLE
Checksum interface

### ISSUE THREAD

**Issue by gibix** [crate-ci/stager#27]
A common pattern is how to generate checksums for witch files.

Minimum support:
- sha1, sha256, sha512(?)
- md5

Target:
- file
- directories (recursively)
- package

Result:
- `HashMap<Path, Manfest>`

**Comment by epage** [comment]
So it sounds like this request is for an API that will generate a manifest for the given set of staged files.

So one question is if this fits in stager or should be separate.  The advantage of being separate is it decouples the policy of what checksum algorithms are supported so they can evolve independently (ie break semver without stager breaking semver).

On the other hand, for https://github.com/crate-ci/cargo-tarball/issues/3 it might be useful to generate a checksum directly on the stager representation.

So a bit undecided if it belongs in this crate or a related crate but definitely something needed.

**Comment by gibix** [comment]
Better to implement it in a seperate crate. Closing here.
